name: run units target on UBI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        tag: ['8' ]

    runs-on: ubuntu-latest

    container: registry.access.redhat.com/ubi${{ matrix.tag }}:latest

    steps:
      - run: dnf install -y --enablerepo=ubi-${{ matrix.tag }}-appstream-rpms --enablerepo=ubi-${{ matrix.tag }}-baseos-rpms --enablerepo=ubi-${{ matrix.tag }}-codeready-builder-rpms git python3 gcc automake autoconf pkgconfig make libxml2-devel libyaml-devel pcre2-devel findutils diffutils sudo file

      # this is to fix https://github.com/actions/checkout/issues/760
      - run: git config --global --add safe.directory /__w/ctags/ctags

      - uses: actions/checkout@v4

      - run: cc --version

      - run: ./autogen.sh
      - run: ./configure --prefix=/usr
      - run: make
      - run: make install
      - run: file /usr/bin/ctags
      - run: ctags --version
      - run: make check V=1
      - run: make roundtrip
