name: 🐛 Bug Report
description: Report a bug in the Milvus RAG system
title: "[BUG] "
labels: ["bug", "triage"]

body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Vector Store (Milvus)
        - Graph Store (Neo4j)
        - NLP Processing
        - Embedding Service
        - RAG System Orchestration
        - Docker/Infrastructure
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Development Phase
      description: Which development phase are you working on?
      options:
        - Phase 1 - Foundation Optimization
        - Phase 2 - Hybrid Integration
        - Phase 3 - Intelligence Layer
        - Phase 4 - Production Excellence
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run command '...'
        2. Query with '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS: [e.g., Ubuntu 22.04 on WSL]
        - Python Version: [e.g., 3.9.7]
        - Milvus Version: [e.g., 2.3.0]
        - Neo4j Version: [e.g., 5.15]
        - Docker Version: [e.g., 24.0.6]
    validations:
      required: true
