name: 🚀 Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement", "triage"]

body:
  - type: dropdown
    id: phase
    attributes:
      label: Target Phase
      options:
        - Phase 1 - Foundation Optimization
        - Phase 2 - Hybrid Integration
        - Phase 3 - Intelligence Layer
        - Phase 4 - Production Excellence
        - Future/Backlog
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
    validations:
      required: true
