---

# .github/workflows/dependabot-auto-merge.yml
name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if PR is ready for auto-merge
      id: check
      run: |
        # Only auto-merge patch and minor updates
        if echo "${{ github.event.pull_request.title }}" | grep -E "(patch|minor)"; then
          echo "auto_merge=true" >> $GITHUB_OUTPUT
        else
          echo "auto_merge=false" >> $GITHUB_OUTPUT
        fi

    - name: Enable auto-merge
      if: steps.check.outputs.auto_merge == 'true'
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on major updates
      if: steps.check.outputs.auto_merge == 'false'
      run: |
        gh pr comment "${{ github.event.pull_request.number }}" --body "🔍 **Major dependency update detected** - requires manual review before merging."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
